In [ ]:
from itertools import combinations
from collections import Counter
import itertools

def find_subsets_with_sum(values, r, target_sum):
    subsets = []
    
    for subset in combinations(values, r):
        if sum(subset) == target_sum:
            subsets.append(subset)
    return subsets

def look_up_func(hand,ranks):

    values = [i+1 for i, count in enumerate(ranks) for _ in range(count)]
    return [find_subsets_with_sum(values,r,11-int(hand)) for r in range(1, 8)]
    


hand = '3'
ranks = '4002000100'

# HANDS = [f'{i}' for i in range(1,11)]
# RANKS = list(itertools.product(range(5), repeat=10))

def look_up_t(hand, ranks):

    ranks_digit = [int(ranks[i]) for i in range(10)]
    look_up_t = [find_subsets_with_sum(ranks_digit,r,11-int(hand)) for r in range(1, 8)]
    pools = []
    hist = []
    for item in look_up_t:

        if len(item)>0:
            for sub_item in item:
                print(sub_item)
                sub_item = sorted([f'{i}' for i in sub_item])
                if sub_item not in hist:
                    hist.append(sub_item)
                    print(sub_item)
                    pools.append(dict(Counter(sub_item)))
    

    return pools 

look_up_t(hand, ranks)
# res = [
#     {str(key): value for key, value in Counter(subset).items()}
#     for subsets in look_up_t
#     for subset in subsets
# ]
    
    
# res = {
#     hand: {
#         ranks: look_up_func(hand, ranks)
#         for ranks in RANKS if ranks[hand] < 4
#     }
#     for hand in HANDS
# }


In [ ]:
import  torch 
c_edg = torch.tensor([2,2,2,3,3])
t_edg = torch.tensor([0,1,2,0,1,2,3,4,3,4,3,4])
t_sgm = torch.tensor([1,1,1,1,1,1,1,1,1,1,1,1], dtype=torch.float32)
t_inv = torch.argsort(t_edg,stable=True)
t_idx = torch.empty_like(t_inv)
t_idx[t_inv]  = torch.arange(len(t_inv))
i_max         = c_edg.max()
t_msk         = torch.arange(i_max).unsqueeze(0) < c_edg.unsqueeze(1)
t_mtx         = torch.zeros_like(t_msk, dtype=t_sgm.dtype)
t_mtx[t_msk]  = t_sgm[t_inv]
t_smp         = torch.multinomial(t_mtx, num_samples=1).squeeze(1)

In [5]:
import os

file_path = '../STRG/nns/CFR0_TRV0_EXT0.pt.zst'
size_bytes = os.path.getsize(file_path)
size_mb = size_bytes / (1024 * 1024)

print(f"File size: {size_bytes} bytes ({size_mb:.2f} MB)")


File size: 981165 bytes (0.94 MB)


In [15]:
import os 
from Utils import partition_folder
path = '../ADVT/nns/'
gp = partition_folder(path,40)

Group 1: 1 files, 42.78 MB
Group 2: 3 files, 38.58 MB
Group 3: 4 files, 34.80 MB
Group 4: 9 files, 38.41 MB
Group 5: 14 files, 38.51 MB
Group 6: 18 files, 38.26 MB
Group 7: 24 files, 39.81 MB
Group 8: 32 files, 39.98 MB
Group 9: 51 files, 39.65 MB
Group 10: 44 files, 16.49 MB


In [16]:
gp

[['../ADVT/nns/CFR5_TRV1_EXT1.pt.zst'],
 ['../ADVT/nns/CFR0_TRV6_EXT1.pt.zst',
  '../ADVT/nns/CFR3_TRV8_EXT1.pt.zst',
  '../ADVT/nns/CFR7_TRV3_EXT1.pt.zst'],
 ['../ADVT/nns/CFR3_TRV0_EXT1.pt.zst',
  '../ADVT/nns/CFR1_TRV8_EXT0.pt.zst',
  '../ADVT/nns/CFR7_TRV1_EXT1.pt.zst',
  '../ADVT/nns/CFR1_TRV5_EXT1.pt.zst'],
 ['../ADVT/nns/CFR0_TRV2_EXT0.pt.zst',
  '../ADVT/nns/CFR8_TRV7_EXT1.pt.zst',
  '../ADVT/nns/CFR4_TRV9_EXT1.pt.zst',
  '../ADVT/nns/CFR5_TRV9_EXT0.pt.zst',
  '../ADVT/nns/CFR8_TRV8_EXT1.pt.zst',
  '../ADVT/nns/CFR6_TRV0_EXT1.pt.zst',
  '../ADVT/nns/CFR4_TRV1_EXT1.pt.zst',
  '../ADVT/nns/CFR5_TRV9_EXT1.pt.zst',
  '../ADVT/nns/CFR9_TRV1_EXT1.pt.zst'],
 ['../ADVT/nns/CFR4_TRV4_EXT0.pt.zst',
  '../ADVT/nns/CFR9_TRV3_EXT1.pt.zst',
  '../ADVT/nns/CFR5_TRV7_EXT1.pt.zst',
  '../ADVT/nns/CFR7_TRV7_EXT1.pt.zst',
  '../ADVT/nns/CFR5_TRV3_EXT0.pt.zst',
  '../ADVT/nns/CFR8_TRV5_EXT1.pt.zst',
  '../ADVT/nns/CFR4_TRV3_EXT1.pt.zst',
  '../ADVT/nns/CFR9_TRV3_EXT0.pt.zst',
  '../ADVT/nns/CFR3_T

In [7]:
import torch

t1 = torch.ones(2)     # t1 = tensor([1., 1.])
t2 = t1                # t2 now points to the same tensor as t1
t1 = torch.zeros(2)    # t1 is now reassigned to a new tensor


In [ ]:
import torch

N = 3  # Example size
tensor = torch.randint(low=0, high=2, size=(N, 4, 5)) # Replace with your tensor

# Reshape to (N * 52, 4) to get all (4,) tensors
# Each tensor along dim 1 for each N and 52 is now a row
reshaped = tensor.permute(0, 2, 1).reshape(-1, 4)  # Shape: (N * 52, 4)

# .permute(0, 2, 1).reshape(-1, 4).unique(reshaped, dim=0)
# Find unique tensors
unique_tensors = torch.unique(reshaped, dim=0)  # Shape: (M, 4), where M is the number of unique tensors

# Print results
print(f"Number of unique tensors: {unique_tensors.shape[0]}")
print("Unique tensors:\n", unique_tensors)

In [ ]:
for i in range(N):
    for j in range(5):

        print(tensor[i,:,j])

In [ ]:
crd_cntr = {'4': {'4♠', '4♣'}, '5': {'5♣'}} 
pool = {'5': 1, '4': 1}
# *[list(itertools.combinations(crd_cntr[key], pool[key]))
#                              for key in crd_cntr.keys()]

[set(itertools.chain.from_iterable(nested_tuple)) 
        for nested_tuple in 
        itertools.product(*[itertools.combinations(crd_cntr[key], pool[key]) 
                             for key in crd_cntr.keys()])]


In [ ]:
import torch
from torch_geometric.data import Data

edge_index = torch.tensor([[0, 1, 1, 2],
                           [1, 0, 2, 1]], dtype=torch.long)
x = torch.tensor([[-1], [0], [1]], dtype=torch.float)

data = Data(x=x, edge_index=edge_index)


In [ ]:
import torch 
indices = torch.tensor([0, 1], device='cuda:0')
for start, end in zip(indices[:-1], indices[1:]): 
    print(start)
    print(end)

In [ ]:
hand = '3'
ranks = '4002000100'

values = [i+1 for i, count in enumerate(ranks_digit) for _ in range(count)]

In [ ]:
import torch 
TYPE = torch.uint8

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
score = torch.zeros((1,8),dtype=TYPE, device=device)

In [ ]:
lst = [[0, 1], [0, 1, 2]]  # Example input

# Step 1: Convert list to dictionaries
dict_list = [{val: idx for idx, val in enumerate(sublist)} for sublist in lst]

# Step 2: Compute the union of all sets of dictionary keys
union_set = set().union(*[d.keys() for d in dict_list])

print("List of Dictionaries:", dict_list)
print("Union of All Sets:", union_set)


In [ ]:
# Input dictionary
crd_cntr = {'1': [1, 2, 3, 4], '4': [1, 2], '8': [1]}

# Generate the ranks list with list comprehension
ranks = ''.join(map(str, [len(crd_cntr.get(str(i), [])) for i in range(1,11)]))

print(ranks)


In [ ]:
import itertools

# Initialization
HANDS = [f'{i}' for i in range(1, 11)]
RANKS = [dict(zip(HANDS, x)) for x in itertools.product(range(5), repeat=10)]
res = {hand: {} for hand in HANDS}

# Vectorized dictionary comprehension
res = {
    hand: {
        ranks: look_up_func(hand, ranks)
        for ranks in RANKS if ranks[hand] < 4
    }
    for hand in HANDS
}


In [ ]:
import torch

# Example tensor (4, 3, 2)
Z = torch.tensor([
    [[1, 2], [3, 4], [5, 6]],
    [[1, 2], [7, 8], [5, 6]],
    [[9, 10], [3, 4], [11, 12]],
    [[9, 10], [7, 8], [13, 14]]
])

# Step 1: Reshape to (12, 2) for unique computation
flattened_Z = Z.reshape(-1, Z.size(-1))  # (12, 2)

# Step 2: Find unique rows (dim=0) and inverse indices
unique_rows, inverse_indices = torch.unique(
    flattened_Z,
    dim=0,
    return_inverse=True
)

# Step 3: Reshape inverse_indices back to (4, 3)
unique_indices_original_shape = inverse_indices.reshape(Z.shape[0], Z.shape[1])

print("Unique rows (no duplicates):\n", unique_rows)
print("Original tensor's row-to-unique mapping:\n", unique_indices_original_shape)



In [ ]:
unique_indices_original_shape

In [ ]:
pool_numeric_cards = ['2a','2b']
from collections import Counter
pool_numeric_cards_ranks = Counter(card[0] for card in pool_numeric_cards)

In [ ]:
import itertools
king_cards = ['K']
pool_king_cards = ['K0','K1']

p = 0
[{f'p{p}_side':hand, f'pool_side':set(pool)} for hand,pool in itertools.product(king_cards,pool_king_cards)]

In [ ]:
import itertools
pool_num = ['2a','2b','3a']
ranks = {card[0]:card[1] for card in pool_num}


In [ ]:
from collections import defaultdict

ranks = defaultdict(set)  # Each key maps to a set
ranks['2'].add('a')       # This works because ranks['2'] is a set


In [ ]:
crd_cntr = {'1':{'1a','1b'},'2':{'2a'},'3':{'3a','3b'}}
ranks = {'1':1,'2':1,'3':2}
xx = [tuple(itertools.chain.from_iterable(nested_tuple)) 
      for nested_tuple in itertools.product(*[itertools.combinations(crd_cntr[f'{key}'], pool[f'{key}']) for key in range(1,4)])]

# [list(itertools.combinations(crd_cntr[key], value)) for key,value in pool.items()]

In [ ]:
from itertools import product

# Input dictionary
# x = {'0': 3, '1': 2, '2': 1, '3': 2, '4': 1, '5': 1, '6': 1, '7': 1, '8': 1, '9': 1, '10': 1}
x = {'3': 2, '4': 1, '5': 1, '6': 1, '7': 1}
hand = 11

# Create a list of possible values for each index (0 to 10) based on x[i]
ranges = [range(x[key] + 1) for key in x.keys()]

# Generate all possible combinations of values
valid_combinations = []
for combination in product(*ranges):
    if sum(idx * count for idx, count in enumerate(combination)) == hand:
        valid_combinations.append(combination)

# Display the result
print(f"Number of valid combinations: {len(valid_combinations)}")
for comb in valid_combinations:
    print(comb)


aa.items()

In [ ]:
import torch
K = 10 
tt = torch.zeros(K, 1000)

In [ ]:
import numpy as np 
sum([np.log(i) for i in range(1,53)])

In [ ]:
import torch

# Input tensors (shape [2, 4])
input_tensor = torch.tensor([[0, 1, 1, 0],
                             [1, 0, 0, 1]], device='cuda')  # Move to GPU

# Identify indices where elements are 1
indices1 = (input_tensor[0] == 1).nonzero(as_tuple=False).squeeze(-1)
indices2 = (input_tensor[1] == 1).nonzero(as_tuple=False).squeeze(-1)

grid1, grid2 = torch.meshgrid(indices1, indices2, indexing='ij')
combinations = torch.stack([grid1.flatten(), grid2.flatten()], dim=-1)
num_combinations = combinations.size(0)
output_tensor = torch.zeros((num_combinations, *input_tensor.shape), device='cuda')

rows = torch.arange(num_combinations, device='cuda')
output_tensor[rows, 0, combinations[:, 0]] = 1
output_tensor[rows, 1, combinations[:, 1]] = 1

# Print results
output_tensor[0]


In [ ]:
import torch

# Input tensor (shape [2, 8])
input_tensor = torch.tensor([[0, 1, 1, 0, 0, 1, 1, 0],
                             [1, 0, 0, 1, 1, 0, 0, 1]], device='cuda')  # On GPU

# Define the groups
groups = [slice(0, 4), slice(4, 8)]  # Define the column slices for groups

# Process both groups simultaneously
indices = [(input_tensor[:, group] == 1).nonzero(as_tuple=False) for group in groups]

# Separate indices for rows and columns for each group
indices1_row, indices1_col = indices[0][:, 0], indices[0][:, 1]
indices2_row, indices2_col = indices[1][:, 0], indices[1][:, 1]

# Generate all combinations of columns within each group
grid1_col, grid2_col = torch.meshgrid(indices1_col, indices2_col, indexing='ij')
grid1_row, grid2_row = torch.meshgrid(indices1_row, indices2_row, indexing='ij')

# Flatten the grids to get all combinations
grid1_flat = torch.stack([grid1_row.flatten(), grid1_col.flatten()], dim=1)
grid2_flat = torch.stack([grid2_row.flatten(), grid2_col.flatten()], dim=1)

# Prepare output tensors
num_combinations = grid1_flat.size(0)
output = torch.zeros((num_combinations, 2, 8), device='cuda')

# Scatter values for both groups
output[torch.arange(num_combinations), grid1_flat[:, 0], grid1_flat[:, 1]] = 1
output[torch.arange(num_combinations), grid2_flat[:, 0], grid2_flat[:, 1] + 4] = 1

# Print results
output[0]


In [ ]:
import torch

# Input tensor (shape [2, 8])
input_tensor = torch.tensor([[0, 1, 1, 0, 0, 1, 1, 0],
                             [1, 0, 0, 1, 1, 0, 0, 1]], device='cuda')  # On GPU

# Define the groups
groups = [slice(0, 4), slice(4, 8)]  # Define the column slices for groups

# Process both groups to find the indices where elements are 1
indices = [(input_tensor[:, group] == 1).nonzero(as_tuple=False) for group in groups]

# Stack all indices together for efficient computation
group1_indices = indices[0]
group2_indices = indices[1]

# Generate all combinations of indices using broadcasting
group1_indices = group1_indices[:, None, :]  # Add a new dimension for broadcasting
group2_indices = group2_indices[None, :, :]  # Add a new dimension for broadcasting

all_combinations = torch.cat([
    group1_indices.expand(-1, group2_indices.size(1), -1),
    group2_indices.expand(group1_indices.size(0), -1, -1)
], dim=-1)  # Shape: [num_combinations_group1, num_combinations_group2, 4]

# Reshape combinations to flatten
all_combinations = all_combinations.view(-1, 4)

# Prepare output tensor
num_combinations = all_combinations.size(0)
output = torch.zeros((num_combinations, 2, 8), device='cuda')

# Scatter values for both groups in the output tensor
output[torch.arange(num_combinations), all_combinations[:, 0], all_combinations[:, 1]] = 1
output[torch.arange(num_combinations), all_combinations[:, 2], all_combinations[:, 3] + 4] = 1

# Print results
print(output)


In [ ]:
import torch

# Example input tensor of shape [2, 8] on GPU
input_tensor = torch.tensor([
    [0, 1, 1, 0, 0, 1, 1, 0],
    [1, 0, 0, 1, 1, 0, 0, 1]
], device='cuda')

# Define the column slices for the two groups
groups = [slice(0, 4), slice(4, 8)]

# For each group, find indices (row, col_in_group) where entries are 1
indices = [
    (input_tensor[:, grp] == 1).nonzero(as_tuple=False)
    for grp in groups
]
# indices[0] -> shape [N1, 2], each row is [row, col_in_group_0..3]
# indices[1] -> shape [N2, 2], each row is [row, col_in_group_0..3]

group1_indices = indices[0]  # [N1, 2]
group2_indices = indices[1]  # [N2, 2]

# We will combine every row from group1_indices with every row from group2_indices
# Broadcasting approach:
#   group1_indices => shape [N1, 2] -> [N1, 1, 2]
#   group2_indices => shape [N2, 2] -> [1, N2, 2]
# Expanding and concatenating them gives all combinations [N1, N2, 4].
g1 = group1_indices[:, None, :]  # [N1, 1, 2]
g2 = group2_indices[None, :, :]  # [1, N2, 2]

# Concatenate along the last dim -> [N1, N2, 4]
# Each entry looks like [row1, col1, row2, col2]
all_combinations = torch.cat([g1.expand(-1, g2.size(1), -1),
                              g2.expand(g1.size(0), -1, -1)], dim=-1)

# Reshape to [N1*N2, 4]
all_combinations = all_combinations.reshape(-1, 4)
num_combinations = all_combinations.size(0)

# Prepare the output of shape [N1*N2, 2, 8]
output = torch.zeros((num_combinations, 2, 8), device='cuda')

# Unpack row/col info
row1 = all_combinations[:, 0]  # row in [0..1]
col1 = all_combinations[:, 1]  # col in [0..3] for group1
row2 = all_combinations[:, 2]  # row in [0..1]
col2 = all_combinations[:, 3]  # col in [0..3] for group2 (need +4 offset in output)

# Use advanced indexing to set ones in the output
idx = torch.arange(num_combinations, device='cuda')
output[idx, row1, col1] = 1
output[idx, row2, col2 + 4] = 1

# Print or inspect the final result
print("Shape of output:", output.shape)  # Should be [N1*N2, 2, 8]
output[0]


In [ ]:
import torch

# Example input tensor (shape [2, 8]) on GPU
input_tensor = torch.tensor(
    [
        [0, 1, 1, 0, 0, 1, 1, 0],
        [1, 0, 0, 1, 1, 0, 0, 1]
    ],
    device='cuda'
)

# 1) Identify column indices where elements are 1 for each row
indices_row0 = (input_tensor[0] == 1).nonzero(as_tuple=False).flatten()
indices_row1 = (input_tensor[1] == 1).nonzero(as_tuple=False).flatten()

# 2) Generate all possible combinations of those column indices
grid0, grid1 = torch.meshgrid(indices_row0, indices_row1, indexing='ij')
combinations = torch.stack([grid0.flatten(), grid1.flatten()], dim=-1)
num_combinations = combinations.size(0)

# 3) Prepare the output tensor of shape [num_combinations, 2, 8]
output_tensor = torch.zeros((num_combinations, 2, 8), device='cuda')

# 4) Scatter values into the output tensor
batch_indices = torch.arange(num_combinations, device='cuda')
output_tensor[batch_indices, 0, combinations[:, 0]] = 1
output_tensor[batch_indices, 1, combinations[:, 1]] = 1

# Example: print the first combination
print("Output shape:", output_tensor.shape)    # e.g. [num_pairs, 2, 8]
print("First combination:\n", output_tensor[2])


In [ ]:
import torch

# Example input tensor on GPU (shape [2, 8])
input_tensor = torch.tensor(
    [
        [0, 1, 1, 0, 0, 1, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 1]
    ],
    device='cuda'
)

# Split columns into two groups:
# Group A -> columns [0..3], Group B -> columns [4..7]
# We'll gather all valid combinations for each group and then combine them.

def get_group_combinations(tensor_2xM, col_start, col_end):
    """
    Given a 2xM tensor, extract the columns [col_start:col_end],
    find all combinations of 1's for row0 and row1 within that group,
    and return a result of shape [num_combinations, 2, original_num_cols].

    The returned tensor has zeros everywhere except in the group slice,
    where each row has exactly one '1' at one of the valid column indices.
    """
    # 1) Identify column indices (within group) where each row is 1
    sub_tensor = tensor_2xM[:, col_start:col_end]  # shape [2, group_width]
    indices_row0 = (sub_tensor[0] == 1).nonzero(as_tuple=False).flatten()
    indices_row1 = (sub_tensor[1] == 1).nonzero(as_tuple=False).flatten()

    # 2) Generate all combinations of these column indices (no loops)
    grid0, grid1 = torch.meshgrid(indices_row0, indices_row1, indexing='ij')
    combos = torch.stack([grid0.flatten(), grid1.flatten()], dim=-1)
    num_combos = combos.size(0)

    # 3) Prepare an output of shape [num_combos, 2, original_num_cols], all zeros
    original_num_cols = tensor_2xM.size(1)
    output = torch.zeros((num_combos, 2, original_num_cols), device=tensor_2xM.device)

    # 4) Scatter '1's into the correct columns, offset by col_start
    # combos[:, 0] are valid columns for row 0 in the group slice
    # combos[:, 1] are valid columns for row 1 in the group slice
    batch_indices = torch.arange(num_combos, device=tensor_2xM.device)
    output[batch_indices, 0, combos[:, 0] + col_start] = 1
    output[batch_indices, 1, combos[:, 1] + col_start] = 1

    return output

# --- Compute Combinations for Each Group Separately ---

# Group A: columns [0..3]
groupA_output = get_group_combinations(input_tensor, col_start=0, col_end=4)
# Group B: columns [4..7]
groupB_output = get_group_combinations(input_tensor, col_start=4, col_end=8)

# --- Concatenate Results Along the Batch Dimension ---
# We simply stack all the valid combos from Group A and Group B
final_output = torch.cat([groupA_output, groupB_output], dim=0)

print("Final output shape:", final_output.shape)
# E.g. [num_combos_A + num_combos_B, 2, 8]

# Let's look at the first few combos for illustration
for i in range(min(8, final_output.size(0))):
    print(f"Combination {i}:\n", final_output[i])


In [ ]:
import torch

# Suppose input_tensor has shape [2, 8], on CUDA
input_tensor = torch.tensor([
    [0, 1, 1, 0, 0, 1, 1, 0],  # row 0
    [1, 1, 0, 0, 0, 0, 0, 0]   # row 1 with no 1s (example)
], device='cuda')

# Identify column indices where each row has 1
indices_row0 = (input_tensor[0] == 1).nonzero(as_tuple=False).flatten()
indices_row1 = (input_tensor[1] == 1).nonzero(as_tuple=False).flatten()

# If row1 has no '1's, we produce a one-sided output
if indices_row1.numel() == 0:
    # We have len(indices_row0) valid positions in row0
    # For each position, create a slice with row0=1 at that position, row1=all zeros
    num_combinations = indices_row0.size(0)
    
    # Prepare the output: [num_combinations, 2, 8]
    output_tensor = torch.zeros((num_combinations, 2, input_tensor.shape[1]), device='cuda')
    
    batch_idx = torch.arange(num_combinations, device='cuda')
    output_tensor[batch_idx, 0, indices_row0] = 1
    # Row 1 stays zero, so nothing else to do

else:
    # Standard pairwise logic via meshgrid
    grid0, grid1 = torch.meshgrid(indices_row0, indices_row1, indexing='ij')
    combos = torch.stack([grid0.flatten(), grid1.flatten()], dim=-1)
    num_combinations = combos.size(0)
    
    output_tensor = torch.zeros((num_combinations, 2, input_tensor.shape[1]), device='cuda')
    batch_idx = torch.arange(num_combinations, device='cuda')
    output_tensor[batch_idx, 0, combos[:, 0]] = 1
    output_tensor[batch_idx, 1, combos[:, 1]] = 1

# Print the results
print("Output shape:", output_tensor.shape)
print("Output tensor:\n", output_tensor)


In [ ]:
import torch

# Example 2x8 input on GPU
# Row 0 has some '1's in both block A ([0..3]) and block B ([4..7])
# Row 1 also has some '1's in both blocks
input_tensor = torch.tensor(
    [
        [0, 1, 1, 0, 0, 1, 1, 0],  # row 0
        [1, 0, 0, 1, 1, 0, 0, 1]   # row 1
    ],
    device='cuda'
)

# 1) Find all column indices where row0 == 1 and row1 == 1
idx0 = (input_tensor[0] == 1).nonzero(as_tuple=False).flatten()
idx1 = (input_tensor[1] == 1).nonzero(as_tuple=False).flatten()

# 2) Generate the Cartesian product of idx0, idx1 (no loops)
grid0, grid1 = torch.meshgrid(idx0, idx1, indexing='ij')
combos = torch.stack([grid0.flatten(), grid1.flatten()], dim=-1)  # shape [N0*N1, 2]

# 3) Mask out cross-block combos
#    Keep only pairs where both columns are in [0..3] or both in [4..7]
mask = (
    ((combos[:, 0] < 4) & (combos[:, 1] < 4)) |    # both in block A
    ((combos[:, 0] >= 4) & (combos[:, 1] >= 4))    # both in block B
)
combos = combos[mask]

# 4) Scatter into the final tensor of shape [num_combos, 2, 8]
num_combos = combos.size(0)
output_tensor = torch.zeros((num_combos, 2, 8), device='cuda')
batch_idx = torch.arange(num_combos, device='cuda')

# row=0 => combos[:,0], row=1 => combos[:,1]
output_tensor[batch_idx, 0, combos[:, 0]] = 1
output_tensor[batch_idx, 1, combos[:, 1]] = 1

print("Output tensor shape:", output_tensor.shape)   # e.g. [num_combos, 2, 8]
print("Example combination:\n", output_tensor)


In [ ]:
import torch



def build_block_combos(row0_indices, row1_indices, offset, total_cols, device):
    """
    Build all combinations for a single block (of width 4).
    - `row0_indices`: columns (0..3 relative) in this block where row0 == 1
    - `row1_indices`: columns (0..3 relative) in this block where row1 == 1
    - `offset`: 0 for block A, 4 for block B
    - `total_cols`: 8 in a 2x8 tensor
    - Returns: [N, 2, total_cols], each slice has one '1' in row0 & row1 (same block),
      or single-sided if `row1_indices` is empty.
    """
    # If row1 has no valid columns in this block => single-sided combos for row0
    if row1_indices.numel() == 0:
        num_combos = row0_indices.size(0)
        out = torch.zeros((num_combos, 2, total_cols), device=device)
        batch = torch.arange(num_combos, device=device)
        # Place '1' for row0 at each valid column + offset
        out[batch, 0, row0_indices + offset] = 1
        return out

    # Otherwise, we do the normal pairwise meshgrid for row0 & row1 columns in this block
    grid0, grid1 = torch.meshgrid(row0_indices, row1_indices, indexing='ij')
    combos = torch.stack([grid0.flatten(), grid1.flatten()], dim=-1)  # [N0*N1, 2]

    num_combos = combos.size(0)
    out = torch.zeros((num_combos, 2, total_cols), device=device)
    batch = torch.arange(num_combos, device=device)

    # Scatter '1's: row0 => combos[:,0] + offset, row1 => combos[:,1] + offset
    out[batch, 0, combos[:, 0] + offset] = 1
    out[batch, 1, combos[:, 1] + offset] = 1
    return out

def build_no_cross_combos_2x8(input_2x8: torch.Tensor) -> torch.Tensor:
    """
    Build all valid combinations for a 2x8 tensor, ensuring no cross-block (A->B or B->A).
    - Block A: columns [0..3]
    - Block B: columns [4..7]
    - If row1 has no valid columns in a block, produce single-sided combos for row0 in that block.
    - Returns [N, 2, 8].
    """
    device = input_2x8.device
    total_cols = input_2x8.shape[1]  # 8

    # --- Gather block A indices ---
    row0_A = (input_2x8[0, :4] == 1).nonzero(as_tuple=False).flatten()  # col indices in [0..3]
    row1_A = (input_2x8[1, :4] == 1).nonzero(as_tuple=False).flatten()

    # --- Gather block B indices ---
    row0_B = (input_2x8[0, 4:] == 1).nonzero(as_tuple=False).flatten()  # col indices in [0..3] for that slice
    row1_B = (input_2x8[1, 4:] == 1).nonzero(as_tuple=False).flatten()

    # Build combos for block A (offset=0)
    combosA = build_block_combos(row0_A, row1_A, offset=0, total_cols=total_cols, device=device)
    # Build combos for block B (offset=4)
    combosB = build_block_combos(row0_B, row1_B, offset=4, total_cols=total_cols, device=device)

    # Concatenate along the batch dimension
    return torch.cat([combosA, combosB], dim=0)

# Example tensor on GPU
input_tensor = torch.tensor(
    [
        [0, 1, 1, 0, 0, 1, 1, 0],  # row 0
        [1, 0, 0, 1, 0, 0, 0, 0]   # row 1
    ],
    device='cuda'
)

# --------------------
# USAGE EXAMPLE
# --------------------
final_output = build_no_cross_combos_2x8(input_tensor)
print("Final output shape:", final_output.shape)
for i in range(len(final_output)):
    print(f"Combination {i}:\n", final_output[i])


In [ ]:
def build_no_cross_combos_batched(batched_2x8: torch.Tensor):
    """
    For each [i, :, :] slice in a [B, 2, 8] tensor, build the no-cross-block combos
    and collect them in a list. Each element of the list has shape [N_i, 2, 8].
    """
    results = []
    B = batched_2x8.shape[0]
    return [build_no_cross_combos_2x8(batched_2x8[i]) for i in range(B)]
    # for i in range(B):
    #     slice_2x8 = batched_2x8[i]       # shape [2,8]
    #     combos_i = build_no_cross_combos_2x8(slice_2x8)
    #     results.append(combos_i)
    # return results

# Example usage:
input_batched = torch.randint(0, 2, size=(100, 2, 8), device='cuda')  # random 0/1
all_combos = build_no_cross_combos_batched(input_batched)

# 'all_combos' is a Python list of length 100
# each item has shape [N_i, 2, 8], where N_i can differ


In [ ]:
from itertools import combinations
from collections import Counter
import itertools
import torch
import numpy as np 

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

def find_subsets_with_sum(values, r, target_sum):
    subsets = []
    
    for subset in combinations(values, r):
        if sum(subset) == target_sum:
            subsets.append(subset)
            
    return subsets


# hand = '3'


def look_up_t(hand, ranks):

    # ranks_digit = [np.uint8(i+1) for i, count in enumerate([int(ranks[i]) for i in range(10)]) for _ in range(count)] 
    ranks_digit = [i+1 for i, count in enumerate([int(ranks[i]) for i in range(10)]) for _ in range(count)] 
    # import pdb; pdb.set_trace()
    ranks_subsets = [find_subsets_with_sum(ranks_digit,r,11-int(hand)) for r in range(1, 8)]
    # import pdb; pdb.set_trace()
    pools = []
    hist = []
    for item in ranks_subsets:
        # import pdb; pdb.set_trace()
        if len(item)>0:
            for sub_item in item:
                # sorted(sub_item)
                # print(sub_item)
                # import pdb; pdb.set_trace()
                sub_item = sorted(sub_item)
                if sub_item not in hist:
                    hist.append(sub_item)
                    # print(sub_item)
                    # pools.append({key: np.uint8(value) for key, value in Counter(sub_item).items()})
                    pools.append(dict(Counter(sub_item)))
                    # import pdb; pdb.set_trace()
    return pools 


HANDS = [i for i in range(1,11)]
RANKS = [f'{i1}{i2}{i3}{i4}{i5}{i6}{i7}{i8}{i9}{i10}' for i1,i2,i3,i4,i5,i6,i7,i8,i9,i10 in itertools.product(range(5), repeat=10)]
# RANKS = RANKS[:16*5]

# import pdb; pdb.set_trace()

full_res = {
    hand: look_up_t(hand, '4444444444')
    for hand in HANDS
}

In [ ]:
import torch

# Boolean tensor
x = torch.tensor([0, 1, 1, 0], dtype=torch.uint8)
print("x =", x)                 # tensor([ True, False,  True, False])

y = torch.bitwise_not(x)
# same as y = ~x
print("bitwise_not(x) =", y)    # tensor([False,  True, False,  True])


In [ ]:
import torch
import math

# 1. Create the array of "values" for each index i in [0..39].
#    value(i) = ceil(1 + i/4)
vals = torch.tensor([math.floor(1 + i/4) for i in range(40)], dtype=torch.int64)

# We want subsets that sum exactly to 11.
TARGET_SUM = 11
N = 40

# 2. Create a DP table: dp[i, s] is True if we can form sum 's' using first i items.
#    We'll make dp have shape (N+1, TARGET_SUM+1).
dp = torch.zeros((N + 1, TARGET_SUM + 1), dtype=torch.bool)

# Base case: dp[0, 0] = True (subset of size 0 has sum 0).
dp[0, 0] = True

# 3. Fill in the DP table.
#    i goes from 1..N, s goes from 0..TARGET_SUM
for i in range(1, N + 1):
    v = vals[i - 1].item()  # the value of the (i-1)th element
    for s in range(TARGET_SUM + 1):
        # Option 1: Skip this item
        if dp[i - 1, s]:
            dp[i, s] = True
        # Option 2: Take this item (if s >= v)
        elif s >= v and dp[i - 1, s - v]:
            dp[i, s] = True

# Check if there's at least one solution
if not dp[N, TARGET_SUM]:
    print("No subsets sum to 11.")
else:
    print("There is at least one subset summing to 11. Now finding all...")

    # 4. Backtracking to retrieve ALL subsets that yield sum = 11.
    #    This can be large, so be cautious about memory/time usage!

    def backtrack(i, s):
        """
        Yields *all* subsets (as lists of indices) using the first i items
        that sum to s.
        """
        # If we've hit sum=0, we have a valid subset (empty at this stage).
        if s == 0:
            yield []
            return

        # If we've run out of items, no solution from here on.
        if i == 0:
            return

        # Check possibility #1: we did NOT use the i-1 th item.
        if dp[i - 1, s]:
            for subset in backtrack(i - 1, s):
                yield subset

        # Check possibility #2: we used the i-1 th item (if feasible).
        v = vals[i - 1].item()
        if s >= v and dp[i - 1, s - v]:
            for subset in backtrack(i - 1, s - v):
                yield subset + [i - 1]

    all_solutions = []
    for subset_indices in backtrack(N, TARGET_SUM):
        # Build a 0/1 tensor of length 40
        solution_tensor = torch.zeros(N, dtype=torch.uint8)
        for idx in subset_indices:
            solution_tensor[idx] = 1
        all_solutions.append(solution_tensor)

all_solutions_tensor = torch.stack(all_solutions, dim=0)
idx = {i:(all_solutions_tensor[:, i]).nonzero(as_tuple=True)[0] for i in range(40)}


In [ ]:
import torch


x = torch.zeros(40, dtype=torch.uint8)
indices = [1]
x[indices] = 1
x = x.unsqueeze(0)
all_solutions_tensor[idx[39]]
mask_A = ((all_solutions_tensor[idx[39]] & x) == all_solutions_tensor[idx[39]]).all(dim=1)
mask_A

In [ ]:
all_solutions_tensor[idx[39]]

In [ ]:
import torch

def build_block_combos(slice_2x52, col_start, col_end):
    """
    Build combos within columns [col_start:col_end],
    for a 2x52 slice, using our previous block logic:
     - row0 = slice_2x52[0], row1 = slice_2x52[1].
     - single-sided if row1 has no 1s in that block.
    Returns a [N, 2, 52] tensor.
    """
    device = slice_2x52.device
    # Identify columns where row0/row1 == 1 in [col_start..col_end)
    sub_width = col_end - col_start  # usually 4
    row0_indices = (slice_2x52[0, col_start:col_end] == 1).nonzero(as_tuple=False).flatten()
    row1_indices = (slice_2x52[1, col_start:col_end] == 1).nonzero(as_tuple=False).flatten()

    # If row1 has no valid columns => single-sided combos
    if row1_indices.numel() == 0:
        num_combos = row0_indices.size(0)
        out = torch.zeros((num_combos, 2, 52), device=device)
        if num_combos > 0:
            out_idx = torch.arange(num_combos, device=device)
            out[out_idx, 0, row0_indices + col_start] = 1
        return out

    # Otherwise, pairwise combos via meshgrid
    grid0, grid1 = torch.meshgrid(row0_indices, row1_indices, indexing='ij')
    combos = torch.stack([grid0.flatten(), grid1.flatten()], dim=-1)  # shape [N0*N1, 2]
    num_c = combos.size(0)

    out = torch.zeros((num_c, 2, 52), device=device)
    out_idx = torch.arange(num_c, device=device)
    out[out_idx, 0, combos[:, 0] + col_start] = 1
    out[out_idx, 1, combos[:, 1] + col_start] = 1
    return out

def build_no_cross_2x52_in_last_8(slice_2x52):
    """
    For a 2x52 slice, build combos in the last 8 columns ([44..52)):
     - Split into block A = [44..48), block B = [48..52)
     - No cross-block needed here, each block is handled independently
     - Return combosA, combosB (both are [N, 2, 52] but possibly different N).
    """
    # columns [44..48) => block A
    combosA = build_block_combos(slice_2x52, col_start=44, col_end=48)
    # columns [48..52) => block B
    combosB = build_block_combos(slice_2x52, col_start=48, col_end=52)
    return combosA, combosB

def build_single_sided_for_minus12_to_minus8(slice_2x52):
    """
    Look at columns [-12..-8) => [40..44), but only for row0 in our slice_2x52.
    For each '1' in row0[40..44), build a new [2, 52] combo:
      - row0 has '1' at that column (single-sided).
      - row1 is copied from slice_2x52[1, :], except columns [44..52) forced to 0.
    Returns shape [K, 2, 52], one slice per '1' in row0[40..44).
    """
    device = slice_2x52.device
    row0_indices = (slice_2x52[0, 40:44] == 1).nonzero(as_tuple=False).flatten()
    num_combos = row0_indices.size(0)

    # Prepare the output
    out = torch.zeros((num_combos, 2, 52), device=device)

    if num_combos > 0:
        # 1) Copy row1 from the original slice for *each* combo
        out[:, 1, :] = slice_2x52[1]

        # 2) Force row1 columns [44..52) = 0
        out[:, 1, 44:52] = 0

        # 3) Place '1' in row0 at the chosen columns [40..44)
        out_idx = torch.arange(num_combos, device=device)
        out[out_idx, 0, row0_indices + 40] = 1

    return out


def build_for_0x39(slice_2x52):
    """
    Look at columns [-12..-8) => [40..44), but only for row0 in our slice_2x52.
    For each '1' in row0[40..44), build a new [2, 52] combo:
      - row0 has '1' at that column (single-sided).
      - row1 is copied from slice_2x52[1, :], except columns [44..52) forced to 0.
    Returns shape [K, 2, 52], one slice per '1' in row0[40..44).
    """
    device = slice_2x52.device
    row0_indices = (slice_2x52[0,:40] == 1).nonzero(as_tuple=False).flatten()
    # print(row0_indices)
    # num_combos = row0_indices.size(0)
    for index in row0_indices:
        # print(index)
        candidates = all_solutions_tensor[idx[index.item()]]
        # print(candidates)
        mask_A = ((candidates & slice_2x52[0,:40]) == candidates).all(dim=1)

        
        # print(mask_A)
    # print(slice_2x52)
    # # Prepare the output
    # out = torch.zeros((num_combos, 2, 52), device=device)

    # if num_combos > 0:
    #     # 1) Copy row1 from the original slice for *each* combo
    #     out[:, 1, :] = slice_2x52[1]

    #     # 2) Force row1 columns [44..52) = 0
    #     out[:, 1, 44:52] = 0

    #     # 3) Place '1' in row0 at the chosen columns [40..44)
    #     out_idx = torch.arange(num_combos, device=device)
    #     out[out_idx, 0, row0_indices + 40] = 1

    return mask_A

def process_13x52(input_13x52, p):
    """
    Main routine:
      1) Pick which row is 'top' (row0 vs row1) based on p, and the 'bottom' row is row2.
      2) Form a 2x52 slice for those two rows.
      3) Build combosA, combosB in the last 8 columns.
      4) Build single-sided combos for columns [40..44) in top row.
      5) Return them all (not concatenated).
    """
    device = input_13x52.device

    slice_2x52 = input_13x52[[p, 2]]

    # Step 3: combosA, combosB in the last 8 columns
    combosA, combosB = build_no_cross_2x52_in_last_8(slice_2x52)

    # Step 4: single-sided combos for columns [40..44) in top row
    single_sided = build_single_sided_for_minus12_to_minus8(slice_2x52)
    # print(build_for_0x39(slice_2x52))
    # Step 5: Return them separately (not concatenated).
    maks_A = build_for_0x39(slice_2x52)
    return mask_A
    # return combosA, combosB, single_sided




In [ ]:
import torch

def build_block_for_index(index, row0, all_solutions_tensor, idx):
    """
    For a single 'index':
      1) Gather the candidate rows: candidates = all_solutions_tensor[idx[index]]
      2) Build a mask for 'subset' check: (candidate & row0) == candidate
      3) If we have valid rows, stack them with row0 into shape (num_valid, 2, 40)
      4) Otherwise, return shape (1, 2, 40) with row0 on top and zeros on the bottom.

    Returns:
      A tensor of shape (X, 2, 40), where X >= 1.
    """
    # 1) Gather candidate rows
    candidates = all_solutions_tensor[idx[index.item()]]  # shape (M, 40)

    # 2) Vectorized subset check (no per-row Python loop):
    #    We want (candidates <= row0) in a 0/1 sense => (c & row0) == c
    mask_A = ((candidates & row0) == candidates).all(dim=1)  # shape (M,)

    num_valid = mask_A.sum().item()
    if num_valid > 0:
        # 3) Some valid rows => stack them with row0
        valid_rows = candidates[mask_A]  # shape (num_valid, 40)
        # Expand row0 to match num_valid rows, shape (num_valid, 40)
        row0_expanded = row0.unsqueeze(0).expand(num_valid, -1)
        # Stack along a new dim => (num_valid, 2, 40)
        block = torch.stack([row0_expanded, valid_rows], dim=1)
    else:
        # 4) No valid candidates => return (1, 2, 40) with row0 + zeros
        block = torch.zeros((1, 2, 40), dtype=row0.dtype, device=row0.device)
        block[0, :] = row0

    return block

def process_all_indices(row0_indices, row0, all_solutions_tensor, idx):
    """
    For each 'index' in row0_indices, build a block with build_block_for_index().
    Then concatenate blocks along dim=0 into one big tensor (X, 2, 40).
    If row0_indices is empty, return (0, 2, 40).
    """
    blocks = [
        build_block_for_index(ind, row0, all_solutions_tensor, idx) 
        for ind in row0_indices
    ]
    if blocks:
        return torch.cat(blocks, dim=0)
    else:
        return torch.empty((0, 2, 40), dtype=row0.dtype, device=row0.device)



In [ ]:

# Suppose we have a 13x52 tensor on GPU
# We'll just make a random 0/1 example here on CPU for demonstration.
input_13x52 = torch.randint(0, 2, (13, 52))

p = 0  # or 1
combosA, combosB, single_sided, onex40 = process_13x52(input_13x52, p)
mask_A = process_13x52(input_13x52, p)
# print("CombosA shape:", combosA.shape)
# print("CombosB shape:", combosB.shape)
# print("Single-sided shape:", single_sided.shape)

# combosA, combosB, single_sided are each [N, 2, 52] but can have different N.
# They are NOT concatenated here; you can later do so if desired.


In [ ]:
if __name__ == "__main__":
    # Mock data
    slice_2x52 = torch.randint(0, 2, (2, 52), dtype=torch.uint8)
    # Suppose row0 is the first row's first 40 columns
    row0 = slice_2x52[0, :40]

    # row0_indices: positions where row0 == 1
    row0_indices = (row0 == 1).nonzero(as_tuple=True)[0]

    # Now build the final result
    final_result = process_all_indices(row0_indices, row0, all_solutions_tensor, idx)

    print("slice_2x52:\n", slice_2x52)
    print("row0:", row0)
    print("row0_indices:", row0_indices.tolist())
    print("final_result shape:", final_result.shape)
    if final_result.size(0) > 0:
        print("first block:\n", final_result[0])


In [ ]:
torch.zeros((0, 2, 52))[0]

In [ ]:
import random

deck = list(range(52))
random.shuffle(deck)
print(deck)

In [ ]:
deck = torch.tensor(range(52))

In [ ]:
deck

In [ ]:
deck = torch.arange(52,dtype=torch.uint8, device=device)
while True:
    deck = deck[torch.randperm(deck.size(0))]
    if not any([x in [40, 41, 42, 43] for x in deck[4:8] ]):
        break 

In [ ]:
import torch

# Create sparse tensors
indices1 = torch.tensor([[0, 1, 1], [2, 0, 2]])  # Coordinates of non-zero elements
values1 = torch.tensor([3.0, 4.0, 5.0])          # Non-zero values
sparse_tensor1 = torch.sparse_coo_tensor(indices1, values1, (3, 3))

indices2 = torch.tensor([[0, 1], [2, 2]])
values2 = torch.tensor([1.0, 2.0])
sparse_tensor2 = torch.sparse_coo_tensor(indices2, values2, (3, 3))

# Subtract the sparse tensors
result = sparse_tensor1 - sparse_tensor2

# Convert to dense for visualization (optional)
print("Result (dense):")
print(result.to_dense())


In [ ]:
sparse_tensor1

In [ ]:
import torch

# Example dictionary
d = {0: 10, 1: 20, 2: 30, 3: 40, 4: 50}

# Example tensor of indices
tensor_a = torch.tensor([1, 3, 0, 4, 2])  # Indices from the dictionary

# Convert dictionary values to a tensor (lookup table)
max_index = max(d.keys()) + 1  # Ensure all indices fit
lookup_table = torch.zeros(max_index, dtype=torch.long)
for k, v in d.items():
    lookup_table[k] = v

# Efficient lookup using tensor indexing
result = lookup_table[tensor_a]

print(result)  # Output: tensor([20, 40, 10, 50, 30])


In [ ]:
import torch

# Define the indices of nonzero elements (COO format)
indices = torch.tensor([[0, 1, 2],  # Row indices
                        [1, 0, 2]])  # Column indices

# Define the values at those indices
values = torch.tensor([1, 2, 3])  # Values at (0,1), (1,0), and (2,2)

# Define the shape of the sparse tensor
size = (3, 3)

# Create the sparse tensor
sparse_tensor = torch.sparse_coo_tensor(indices, values, size)

print("Sparse Tensor:")
print(sparse_tensor)

# Extracting row 0 indices
row_0_mask = indices[0] == 0  # Select elements from row 0
row_0_indices = indices[1][row_0_mask]  # Get column indices where row = 0

print("Row 0 Indices:", row_0_indices)



In [ ]:
(sparse_tensor+sparse_tensor).to_dense()

In [ ]:
size_map = {0: 20, 1: 100}  # Assign custom sizes
df["marker_size"] = df["binary_column"].map(size_map)

sns.scatterplot(data=df, x="A", y="B", hue="category_column", size="marker_size", sizes=(10, 200))

plt.show()


In [ ]:
import torch

# Define the indices of non-zero elements
indices1 = torch.tensor([[0, 1, 2], [2, 0, 1]])  # COO format: (2 x nnz)
values1 = torch.tensor([1.0, 2.0, 3.0])         # Values of non-zero elements
sparse_tensor1 = torch.sparse_coo_tensor(indices1, values1, size=(3, 3))

indices2 = torch.tensor([[0, 1, 2], [1, 2, 0]])  # COO format: (2 x nnz)
values2 = torch.tensor([4.0, 5.0, 6.0])         # Values of non-zero elements
sparse_tensor2 = torch.sparse_coo_tensor(indices2, values2, size=(3, 3))

# Ensure the sparse tensors are coalesced (recommended for operations)
sparse_tensor1 = sparse_tensor1.coalesce()
sparse_tensor2 = sparse_tensor2.coalesce()
# Perform matrix multiplication
result = torch.sparse.mm(sparse_tensor1, sparse_tensor2)

# Convert the result to a dense tensor for easier inspection (optional)
result_dense = result.to_dense()
print(result_dense)


In [ ]:
import torch

# Create a sparse tensor with duplicate indices
indices = torch.tensor([[0, 1, 0], [2, 0, 2]])  # Duplicate index (0, 2)
values = torch.tensor([1.0, 2.0, 3.0])          # Values for the indices
sparse_tensor = torch.sparse_coo_tensor(indices, values, size=(3, 3))

print("Before coalescing:")
print("Indices:\n", sparse_tensor.indices())
print("Values:\n", sparse_tensor.values())

# Coalesce the sparse tensor
coalesced_tensor = sparse_tensor.coalesce()

print("\nAfter coalescing:")
print("Indices:\n", coalesced_tensor.indices())
print("Values:\n", coalesced_tensor.values())

In [ ]:
import torch

# Create the tensors
tensor1 = torch.rand(8, 2, 4)  # Shape: (8, 2, 40)
tensor2 = torch.randn(4, 7)    # Shape: (40, 27)

# Perform batch matrix multiplication
result = torch.matmul(tensor1, tensor2)  # Shape: (8, 2, 27)

# Alternatively, you can use the @ operator
# result = tensor1 @ tensor2

print("Shape of tensor1:", tensor1.shape)
print("Shape of tensor2:", tensor2.shape)
print("Shape of result:", result.shape)

In [ ]:
import torch

# Create a tensor of shape (N, 2, 40)
N = 3
tensor = torch.arange(N * 2 * 4).reshape(N, 2, 4)  # Example tensor

# Reshape to (2*N, 40)
flattened_tensor = tensor.reshape(2 * N, 4)

print("Original tensor shape:", tensor.shape)
print("Flattened tensor shape:", flattened_tensor.shape)
# Reshape back to (N, 2, 40)
restored_tensor = flattened_tensor.reshape(N, 2, 4)

print("Restored tensor shape:", restored_tensor.shape)

# Check if the restored tensor matches the original
print("Are the tensors equal?", torch.equal(tensor, restored_tensor))

In [ ]:
import torch

# Example tensors
slice_2x40 = torch.randn(8, 2, 40)  # Shape: (8, 2, 40)
all_solutions_tensor = torch.randn(40, 27)  # Shape: (40, 27)

# Add a batch dimension to all_solutions_tensor
all_solutions_tensor_3d = all_solutions_tensor.unsqueeze(0)  # Shape: (1, 40, 27)

# Expand the batch dimension to match slice_2x40
all_solutions_tensor_3d = all_solutions_tensor_3d.expand(slice_2x40.size(0), -1, -1)  # Shape: (8, 40, 27)

# Perform batch matrix multiplication
result = torch.bmm(slice_2x40, all_solutions_tensor_3d)  # Shape: (8, 2, 27)

print("Shape of result:", result.shape)

In [ ]:
import torch
import torch.nn as nn

# Example neural network
class SimpleNet(nn.Module):
    def __init__(self):
        super(SimpleNet, self).__init__()
        self.fc = nn.Linear(10, 1)  # Example layer

    def forward(self, x):
        return self.fc(x)

# Create a tensor of type torch.uint8 (Byte)
uint8_tensor = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=torch.uint8)

# Step 1: Convert to floating-point type
float_tensor = uint8_tensor.to(torch.float32)  # or use .float()

# Step 2: Normalize (if necessary)
# For example, if the tensor represents pixel values in [0, 255], normalize to [0, 1]
float_tensor = float_tensor / 255.0

# Step 3: Pass the tensor to the neural network
model = SimpleNet()
output = model(float_tensor.unsqueeze(0))  # Add batch dimension if needed

print("Output:", output)

In [ ]:
N = 100  # Example value for N
zero_tensor = torch.zeros(8, N, 40)
print(zero_tensor.shape)  # Output: torch.Size([8, N, 40])


In [ ]:
import torch

# Create two tensors of shape [2, 3]
tensor1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor2 = torch.tensor([[7, 8, 9], [10, 11, 12]])

# Element-wise multiplication using the * operator
result = tensor1 * tensor2

# Alternatively, use torch.mul
# result = torch.mul(tensor1, tensor2)

print("Tensor 1:\n", tensor1)
print("Tensor 2:\n", tensor2)
print("Element-wise multiplication result:\n", result)

In [ ]:
import torch

# Example data
cc = torch.randint(0, 2, (3, 7), dtype=torch.bool, device="cuda")  # 8 x 2764 mask
Np = torch.tensor([True, False, True], device="cuda")  # 8-length mask

# Step 1: Select only the rows where Np is True
cc_selected = cc[Np]  # Shape: (num_selected_rows, 2764)

# Step 2: Reshape to (2764 * num_selected_rows,)
cc_reshaped = cc_selected.reshape(-1)

print(cc_selected.shape)  # Expected: (num_selected_rows, 2764)
print(cc_reshaped.shape)  # Expected: (2764 * num_selected_rows,)



In [ ]:
import torch

# Example tensors
zero_tensor = torch.zeros(6, 4)  # Shape (6,4)
result_hand = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
result = torch.tensor([[2, 2, 2, 2], [3, 3, 3, 3], [4, 4, 4, 4]])

# Apply operation
zero_tensor[::2, :] = result_hand * result

print(zero_tensor)


In [ ]:
result_hand

In [ ]:
import torch

# Example tensor (14, 40)
x = torch.randn(4, 3)

# Grouping tensor indicating sum in pairs (shape [7,])
grouping = torch.tensor([2, 2])

# Create an index tensor that will specify where to add the rows
index = torch.repeat_interleave(torch.arange(grouping.size(0)), grouping)  # Shape: [14]
index = index.view(-1, 1).expand(-1, x.size(1))  # Expand to match x's columns

# Create the output tensor of shape [7, 40]
output = torch.zeros(grouping.size(0), x.size(1))

# Sum rows using scatter_add
output.scatter_add_(0, index, x)

print(output.shape)  # Should output torch.Size([7, 40])


In [ ]:
x


In [ ]:
output

In [ ]:
# [-0.5816,  1.4321,  1.0590][ 0.2138, -1.0521, -0.0380]

In [ ]:
-0.5816+0.2138

In [ ]:
import torch

# Example input tensor
I = torch.tensor([[1, 1, 1, 1, 0], [2, 1, 0, 1, 1]])

# Example tensors tk, tq, tj, tn, tn2
tk = torch.arange(10)  # Example tensor
tq = torch.arange(10, 20)
tj = torch.arange(20, 30)
tn = torch.arange(30, 40)
tn2 = torch.arange(40, 50)

# Store the tensors in a list for easy indexing
tensor_list = [tk, tq, tj, tn, tn2]

# Flatten I and use advanced indexing
I_flat = I.flatten()
Z = torch.cat([tensor_list[idx][i].unsqueeze(0) for i, idx in enumerate(I_flat)])

print(Z)


In [ ]:
I_flat

In [ ]:
import torch

# Define tensors (each of shape (2,1))
tk = torch.tensor([[10], [20]])  # Shape (2,1)
tq = torch.tensor([[30], [40]])
tj = torch.tensor([[50], [60]])
tn = torch.tensor([[70], [80]])
tn2 = torch.tensor([[90], [100]])

# Stack tensors to form shape (5, 2, 1)
T = torch.stack([tk, tq, tj, tn, tn2])  # Shape: (5, 2, 1)

# Define index tensor
I = torch.tensor([
    [1, 1, 1, 1, 0], 
    [2, 1, 0, 1, 1]
])

# Expand column indices to match dimensions
rows = I  # Select row indices
cols = torch.zeros_like(I)  # Since tensors have shape (2,1), column index is always 0

# Use advanced indexing to construct Z
Z = T[rows, torch.arange(I.shape[0])[:, None], cols]

print(Z)


In [ ]:
import torch 
dim = 0 
src = torch.rand(size=(4,4,6))
index = torch.randint(low=0,high=4,size=(4,6))

out = torch.zeros_like(index)

for j in range(4):
    for k in range(6):

        out[j,k] = src[index[j,k],j, k]


In [ ]:
out[0,0]

In [ ]:
out

In [ ]:
src = torch.ones((3, 5))
index = torch.tensor([[1, 0, 0,2, 0],[1, 1, 0, 0, 0]])
torch.zeros(2, 5, dtype=src.dtype).scatter_add_(1, index, src)

In [ ]:
index.shape

In [ ]:
import torch

# Input tensor (4x3)
src = torch.tensor([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9],
                    [10, 11, 12]], dtype=torch.float32)

# Index tensor: specifies which rows to sum
# Sum the first two rows (indices 0 and 1) and the last two rows (indices 2 and 3)
index = torch.tensor([0, 0, 1, 1])  # 0 for first two rows, 1 for last two rows

# Target tensor: initialize with zeros
# The shape is (2, 3) because we are summing into 2 groups
out = torch.zeros(2, 3, dtype=torch.float32)

# Perform scatter_add_
out.scatter_add_(0, index.unsqueeze(1).expand_as(src), src)

print(out)

In [ ]:
index.unsqueeze(1).expand_as(src)

In [ ]:
src = torch.ones((2, 5))
index = torch.tensor([[1,1,1,1,1],[1,1,1,1,1]])
torch.zeros(3, 5, dtype=src.dtype).scatter_add_(0, index, src)
# index = torch.tensor([[0, 1, 2, 0, 0], [0, 1, 2, 2, 2]])
# torch.zeros(3, 5, dtype=src.dtype).scatter_add_(0, index, src)

In [ ]:
# (Pdb) hand_moves
# tensor([[0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
#          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
#          0., 0., 0., 0.],
#         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
#          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
#          0., 0., 0., 0.],
#         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
#          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
#          0., 0., 0., 0.],
#         [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
#          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
#          0., 0., 0., 0.],
#         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
#          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
#          0., 0., 0., 0.],
#         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
#          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
#          0., 0., 0., 0.],
#         [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
#          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
#          0., 0., 0., 0.],
#         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
#          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
#          0., 0., 0., 0.],
#         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
#          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
#          0., 0., 0., 0.]], device='cuda:0', dtype=torch.float16)
# (Pdb) hand_moves.shape
# torch.Size([9, 40])
# (Pdb) moves.shape
# torch.Size([9, 40])
# (Pdb) indices
# tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
#          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
#         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
#          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
#         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
#          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
#         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
#          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
#         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
#          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
#         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
#          1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
#         [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
#          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
#         [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
#          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
#         [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
#          2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]], device='cuda:0')

# (Pdb) hand_check.shape
# torch.Size([3, 40])
# (Pdb)

In [ ]:
a = [1, 2, 3]
b = a  # b is just a reference to a
c = list(a)  # Creates a new list, but elements share the same memory

print(hex(id(a)))  # Memory address of list 'a'
print(hex(id(b)))  # Same as 'a' because 'b' is just another reference
print(hex(id(c)))  # Different address because 'c' is a new list

print(hex(id(a[0])))  # Memory address of the first element
print(hex(id(c[0])))  # Same address as 'a[0]' because integers are immutable



In [ ]:
z = torch.tensor([0, 2, 1])
torch.repeat_interleave(torch.arange(len(z)), z)

In [ ]:
import torch

# Example tensor (3 rows, 4 columns)
x = torch.tensor([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

# Permutation indices (new order of rows)
indices = torch.tensor([2, 0, 1])  # Moves row 2 → row 0, row 0 → row 1, row 1 → row 2

# Apply permutation
permuted_x = x[indices]

print(permuted_x)


In [ ]:
import torch

# Creating a 3D tensor of shape (2, 3, 4)
xx = torch.arange(2 * 3 * 4).reshape(2, 3, 4)
print("Original Tensor:\n", xx)

# Applying indexing
result = xx[:, [0, 2], :]

print("\nSelected Tensor:\n", result)


In [ ]:
xx[0,:,:]

In [ ]:
import torch

x = torch.tensor([10, 20, 30])
repeats = torch.tensor([0, 3, 1])  # Number of times to repeat each element

result = torch.repeat_interleave(x, repeats)
print(result)


In [ ]:
import torch 
import math


# torch.manual_seed(10)
RANKS = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K']
SUITS = ['♣', '♦', '♥', '♠'] 
aces_jackes = [True if x in [0,1,2,3,40,41,42,43] else False for x in range(52)]
jackes = [True if x in [40,41,42,43] else False for x in range(52)]

clubs = [True if x in [4*x for x in range(13)] else False for x in range(52)] 


# infoset[-1,:] = deck

## step A

deck = torch.tensor(range(52))
def print_deck(deck):

    ranks = [math.floor(t/4) for t in deck]
    suits = [t.item()%4 for t in deck]
    return [f"{RANKS[rank]}{SUITS[suit]}" for (rank,suit) in zip(ranks,suits)]

In [ ]:
deck.shape

In [ ]:
print_deck(deck)

In [ ]:
for cnt, card in enumerate(print_deck(deck)): print(cnt,card)

In [ ]:
ans = []
for idx,item in enumerate(print_deck(deck)):
    # print(item)
    # break 
    if item[-1] == '♣':
        ans.append(int(idx/4))
    elif item == '10♦':
        ans.append(13)        
    else:
        rank = RANKS.index(item[:-1])
        ans.append(14+rank)
        

In [ ]:
s1 = '123'
s2 = 'as73123'
s1 in s2

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([2, 3, 4])

# Example function
def f(x, y):
    return x < y
result = f(a[:, None], b[None, :]).astype(int)

In [ ]:
import itertools
for p in itertools.product([0, 1, 2], repeat=4):
    break

In [ ]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
t_deck = torch.arange(52, device=device)

# Indices of all clubs: 0, 4, 8, ..., 48
clubs = torch.arange(0, 52, 4, device=device)  # shape [13]

# Non-clubs (the remaining 39 cards)
non_clubs = t_deck[~torch.isin(t_deck, clubs)]  # shape [39]

# Randomly select 7 non-clubs to go with the 13 clubs in the first 20
non_clubs_perm = non_clubs[torch.randperm(non_clubs.size(0))]
extra_7 = non_clubs_perm[:7]
remaining_non_clubs = non_clubs_perm[7:]

# Shuffle the 13 clubs and extra 7, then concatenate with the rest
first_20 = torch.cat([clubs, extra_7])[torch.randperm(20)]
rest = remaining_non_clubs

# Final deck
final_deck = torch.cat([first_20, rest])

In [ ]:
def print_deck(deck):

    ranks = [math.floor(t/4) for t in deck]
    suits = [t.item()%4 for t in deck]
    return [f"{RANKS[rank]}{SUITS[suit]}" for (rank,suit) in zip(ranks,suits)]

print_deck(final_deck)

In [ ]:
import torch

# Suppose t_tot is a 3D tensor. For this example, we'll create one.
# Let's say t_tot has shape (5, 2, 6)
t_tot = torch.arange(5 * 2 * 6).reshape(5, 2, 6)

# Example index tensors
pick = torch.tensor([0, 1, 2])        # shape: [3]
jack_cards = torch.tensor([0, 1, 2, 3])  # shape: [4]

# Adjust shapes for advanced indexing:
# pick -> shape [3, 1]
# jack_cards -> shape [1, 4]
result = t_tot[pick.unsqueeze(1), 0, jack_cards.unsqueeze(0)]

print("Result shape:", result.shape)  # Expected shape: [3, 4]
print(result)


In [ ]:
'K♣', '2♣', '5♣','9♣','7♣', '3♣', 'J♣', '10♣', '4♣', '1♣', '8♣', '6♣', 'Q♣'

In [ ]:
jack_cards.unsqueeze(0)

In [ ]:
# tensor([[[0., 0., 0., 0.],
#          [0., 0., 0., 0.]],

#         [[0., 0., 0., 0.],
#          [0., 0., 0., 0.]],

#         [[1., 1., 0., 0.],
#          [1., 1., 0., 0.]],

#         [[0., 0., 0., 0.],
#          [0., 0., 0., 0.]],

#         [[1., 0., 0., 1.],
#          [1., 0., 0., 1.]]], device='cuda:0', dtype=torch.float16)

In [ ]:
import torch

# Initialize tensors
t_k = torch.zeros(2, 2, 52)  # Shape (2,2,52)
indices = torch.tensor([[51, 48], [51, 49]])  # Shape (2,2)

# Use advanced indexing
batch_idx = torch.arange(2).unsqueeze(1)  # Creates [[0], [1]]
col_idx = torch.arange(2).unsqueeze(0)  # Creates [[0, 1]]

t_k[batch_idx, col_idx, indices] = 1

# Print result
print(t_k)


In [ ]:
batch_idx.shape

In [ ]:
# ['1♥', '8♣', 'J♣', 'K♠']
# ['1♦', '1♠', '4♥', 'K♦']
# ['2♦', '5♥', '5♠', 'K♥']

In [ ]:
indices

In [ ]:
print(t_k[0,0,51] == 1) 
print(t_k[0,1,48] == 1) 
print(t_k[1,0,51] == 1)
print(t_k[1,1,49] == 1)

In [ ]:
['2♦', '5♦', '7♥', '9♥']

['10♥']
['8♦', '9♠', '10♥', 'K♥']
['1♥', '5♥', '6♥', '9♣']
['2♦', '5♦', '7♥', '9♥']

['5♦', '6♥']
['8♦', '9♠', '10♥', 'K♥']
['1♥', '5♥', '6♥', '9♣']
['2♦', '5♦', '7♥', '9♥']

['8♦']
['8♦', '9♠', '10♥', 'K♥']
['1♥', '5♥', '6♥', '9♣']
['2♦', '5♦', '7♥', '9♥']

['5♥']
['8♦', '9♠', '10♥', 'K♥']
['1♥', '5♥', '6♥', '9♣']
['2♦', '5♦', '7♥', '9♥']

['2♦', '9♠']
['8♦', '9♠', '10♥', 'K♥']
['1♥', '5♥', '6♥', '9♣']
['2♦', '5♦', '7♥', '9♥']

['9♣']
['8♦', '9♠', '10♥', 'K♥']
['1♥', '5♥', '6♥', '9♣']
['2♦', '5♦', '7♥', '9♥']

['K♥']
['8♦', '9♠', '10♥', 'K♥']
['1♥', '5♥', '6♥', '9♣']
['2♦', '5♦', '7♥', '9♥']

['1♥', '10♥']
['8♦', '9♠', '10♥', 'K♥']
['1♥', '5♥', '6♥', '9♣']
['2♦', '5♦', '7♥', '9♥']


In [ ]:
import torch
output, inverse_indices = torch.unique(torch.tensor([1, 3, 2, 3], dtype=torch.long), sorted=False, return_inverse=True)

In [ ]:
zz = torch.tensor([1, 3, 2, 3])

In [ ]:
output

In [ ]:
zz[inverse_indices]

In [ ]:
inverse_indices

In [ ]:
import torch

x = torch.randn(2, 3, 4, 5)
y = x.view(2, -1, 5)  # Reshape without allocating new memory

print(x.data_ptr() == y.data_ptr())  # True (same memory location)


In [ ]:
import torch

slice_2x52 = torch.randn(2, 3, 5)  # Original tensor
slice_2x40 = slice_2x52[:, :, 0:2]    # View (no new memory allocated)
print(slice_2x52)
print(slice_2x40)
del slice_2x52  # Delete original tensor

print(slice_2x40)  # Undefined behavior, may cause an error


In [ ]:
import torch

# Example: Boolean tensor of shape (N, 10)
N = 5  # Example value for N
tensor = torch.randint(0, 2, (N, 2), dtype=torch.bool)

# Get the indices of True values
true_indices = torch.nonzero(tensor)

# Count how many True values are in each row
true_counts = true_indices[:, 0].bincount(minlength=4)

print(true_counts)  # Output: Tensor of shape (N,), showing count of True per row


In [ ]:
true_counts[:, 0].bincount(minlength=4)

In [ ]:
import torch
import time

N = 10000
tensor = torch.randn(N, N)  # Large contiguous tensor
tensor_T = tensor.T  # This is non-contiguous

# Contiguous Tensor Computation
start = time.time()
result = torch.matmul(tensor , tensor)  # Element-wise addition
end = time.time()
print("Contiguous Time:", end - start)

# Non-Contiguous Tensor Computation
start = time.time()
result = torch.matmul(tensor_T , tensor_T)  # Element-wise addition
end = time.time()
print("Non-Contiguous Time:", end - start)


In [ ]:
import torch

tensor = torch.tensor([0, 0, 0, 0, 1, 2, 1, 0, 0, 0, 0, 1, 2, 1, 0, 2, 4, 2, 2, 4, 4, 0, 2, 0,
        0, 2, 2])

# Get the indices where the values are nonzero
indices = torch.nonzero(tensor).squeeze()

# Repeat indices according to their values
result = indices.repeat_interleave(tensor[indices])
counts_unique = torch.tensor([3, 2, 2, 2, 1, 1, 1, 3, 2, 2, 2, 1, 1, 1, 3, 1, 2, 1, 1, 2, 2, 4, 2, 1, 1, 2, 2])
print(result.tolist())  # Output: [4, 5, 5, 6, 11, 12, 12, 13, 15, 15]


In [ ]:
counts_unique[tensor>0]

In [ ]:
tensor[tensor>0].sum()

In [ ]:
counts_unique[tensor>0].sum()

In [ ]:
# cnts_n_unique[0] 
# tensor([0, 3, 4], device='cuda:0')
# (Pdb) cnts_n_v2[0]
# tensor([4, 0, 4, 3], device='cuda:0')
# (Pdb) inverse_indices
# tensor([2, 0, 2, 1], device='cuda:0')

# here is what I need:

# i have a tensor zz = ts_n_unique[0]. I need to construct another tensor xx where the first 4 rows zz[3:3+4], next

In [ ]:
import torch

inverse_indices = torch.tensor([0, 0, 2, 1], device='cuda:0')

cnts_n = torch.tensor([2, 2, 4], device='cuda:0')

cumsum = torch.cumsum(cnts_n,dim=0)
cumsum_max = cumsum[-1] #ts_n_unique[0].shape
arange = torch.arange(cumsum_max, device='cuda:0')
for i in inverse_indices:
    if i == 0:
        print(arange[:cumsum[i]])
    else:
        print(arange[cumsum[i-1]:cumsum[i]])


In [ ]:
import line_profiler

profiler = line_profiler.LineProfiler()
profiler.print_stats()


In [ ]:

# ['2♠', '4♥', '6♦', 'K♦']
# ['1♠', '5♥', '6♥', '8♠']
# ['1♥', '5♠', '10♥', 'Q♠']
# deads
# tensor([3], device='cuda:0') '1♠'

In [ ]:
import torch  # Added missing import
import numpy as np

# Your tensor
tensor = torch.tensor([
    0, 0, 32, 2, 0, 0, 32, 2, 0, 0, 32, 2, 1, 1, 33, 3, 1, 1,
    33, 3, 1, 1, 33, 3, 1, 1, 33, 3, 4, 4, 34, 6, 4, 4, 34, 6,
    4, 4, 34, 6, 4, 4, 34, 6, 5, 5, 35, 7, 5, 5, 35, 7, 5, 5,
    35, 7, 8, 8, 36, 10, 8, 8, 36, 10, 8, 8, 36, 10, 8, 8, 36, 10,
    8, 8, 36, 10, 9, 9, 37, 11, 9, 9, 37, 11, 9, 9, 37, 11, 9, 9,
    37, 11, 9, 9, 37, 11, 12, 12, 38, 14, 12, 12, 38, 14, 12, 12, 38, 14,
    13, 13, 39, 15, 16, 16, 40, 17, 16, 16, 40, 17, 18, 18, 0, 20, 18, 18,
    0, 20, 18, 18, 0, 20, 19, 19, 1, 21, 19, 19, 1, 21, 22, 22, 41, 23,
    22, 22, 41, 23, 22, 22, 41, 23, 22, 22, 41, 23, 24, 24, 42, 25, 24, 24,
    42, 25, 24, 24, 42, 25, 26, 26, 43, 27, 26, 26, 43, 27, 26, 26, 43, 27,
    26, 26, 43, 27, 26, 26, 43, 27, 28, 28, 44, 29, 30, 30, 22, 31, 30, 30,
    22, 31
],device='cuda:0')

# # Dictionary to store the first occurrence of each value
# first_occurrence = {}

# # Iterate through the tensor
# for index, value in enumerate(tensor.tolist()):  # Ensure iteration over Python integers
#     if value not in first_occurrence:  # No need for `.keys()`
#         first_occurrence[value] = index
# first_occurrence.values()
# # Print the first occurrence of each value
# for value, index in sorted(first_occurrence.items()):
#     print(f"First occurrence of {value} is at index {index}")


In [ ]:
[((tensor == i) == True).to(dtype=torch.int8).argmax().item() for i in range(slice_2x40_unique.shape[0])]

In [ ]:
sorted, indices = torch.sort(tensor)

In [ ]:
import torch

# Example input tensor A (size N, with values in the range [1, ..., n])
A = torch.tensor([3, 1, 2, 4, 1, 3, 4, 2], dtype=torch.int64)  # Example with N > n, values in [1, 4]

# Find the size of n (maximum value in A)
n = A.max()

# Create a tensor Z of size n to hold the indices
Z = torch.zeros(n, dtype=torch.int64)

# Populate Z such that A[Z[i]] = i
Z[A - 1] = torch.arange(0, A.size(0), dtype=torch.int64)

print(Z)  # This will print the result vector Z


In [ ]:
import torch

# Example input tensor A (size N, with values in the range [0, ..., n])
A = torch.tensor([3, 0, 2, 4, 0, 3, 4, 1], dtype=torch.int64)  # Example where values are [0, 4]

# Find the size of n (maximum value in A)
n = A.max()

# Create a tensor Z of size n+1 to hold the indices (since 0 is included)
Z = torch.zeros(n + 1, dtype=torch.int64)

# Populate Z such that A[Z[i]] = i (mapping from value to index)
Z[A] = torch.arange(0, A.size(0), dtype=torch.int64)

print(Z)  # This will print the result vector Z


In [ ]:
import torch

# Create a 4x3 tensor
Z = torch.tensor([[10, 11, 12], 
                  [20, 21, 22], 
                  [30, 31, 32], 
                  [40, 41, 42]])

print("Original Tensor:\n", Z)

# Correct way to get the first two rows
first_two_rows = Z[:2]
print("\nFirst two rows using Z[:2]:\n", first_two_rows)

# Incorrect way: Z[[1,2]] selects second and third rows
wrong_selection = Z[[1, 2]]
print("\nWrong selection Z[[1,2]] (second and third rows):\n", wrong_selection)



In [ ]:
import torch

# Example t_tot and valid_mask
t_tot = torch.randn(5, 5, 10)  # Shape (5, 5, 10)
valid_mask = torch.tensor([False, True, False, True, True, False, False, True, False, True])  # Shape (10,)

# Extract z
z = t_tot[:, :, valid_mask]  # Shape (5, 5, number_of_True)

# Find mapping: i -> j
j_indices = torch.nonzero(valid_mask, as_tuple=True)[0]  # Indices where valid_mask is True

# Now, z[:,:,i] corresponds to t_tot[:,:,j_indices[i]]
print(j_indices)  # This gives the mapping


In [ ]:
import torch

a = torch.tensor([2, 3])  # Specifies how to partition b
b = torch.tensor([1, 2, 3, 4, 5])  # Example b tensor

def findsplit(CNT_TOTS):

    def mysplit(a,b):

        b_splits = torch.split(b, a.tolist())
        c = torch.tensor([part.sum() for part in b_splits])
        return c 
    
    a,b = CNT_TOTS[0], CNT_TOTS[1]

    for i in range(2,len(CNT_TOTS)):
        a,b = mysplit(a,b), CNT_TOTS[i]

    return a




print(mysplit(a,b))  # Output: tensor([3, 12])  -> (1+2), (3+4+5)


In [ ]:
import torch.profiler

with torch.profiler.profile(
    activities=[torch.profiler.ProfilerActivity.CPU, torch.profiler.ProfilerActivity.CUDA],
    profile_memory=True,
    record_shapes=True
) as prof:
    x = torch.randn(10000, 10000, device="cuda")
    y = x @ x
    del x, y
    torch.cuda.empty_cache()

print(prof.key_averages().table(sort_by="self_cuda_memory_usage", row_limit=10))





In [ ]:
import torch

# Example boolean tensor
bool_tensor = torch.tensor([False, True, False, True, True, False, False, True])

# Get indices of True values


true_indices = torch.nonzero(bool_tensor, as_tuple=True)[0]  # Extract indices as a 1D tensor
random_index = true_indices[torch.randint(len(true_indices), (1,))].item()


# # Pick one randomly
# if true_indices.numel() > 0:  # Ensure there are True values
    
#     print(random_index)  # Randomly selected index
# else:
#     print("No True values found.")


In [ ]:
torch.randint(len(true_indices), (1,))

In [ ]:
print("\U0001F0A1")  # Using Unicode escape sequence



In [ ]:
import torch

# Creating a sample tensor of shape (2, 3, 4)
Z = torch.arange(2 * 3 * 4).reshape(2, 3, 4)

# Indices for the second and third coordinates
idx2 = torch.tensor([0, 2])
idx3 = torch.tensor([2, 3])

# Using meshgrid to create indexing
grid2, grid3 = torch.meshgrid(idx2, idx3, indexing='ij')

# Extracting the subtensor in one go
subtensor = Z[:, grid2, grid3]

print(subtensor)


In [ ]:
import torch

# Adds all values from the tensor src into self at the indices specified
# Create a target tensor (float type)
target = torch.zeros(5, dtype=torch.float32)  # Ensure float32 type

# Indices where values should be added
index = torch.tensor([2])

# Values to add (must have same dtype as target)
src = torch.tensor([10, 20, 30, 40, 50], dtype=torch.float32)  # Match dtype

# Perform scatter_add_
target.scatter_add_(0, index, src)

print(target)



In [ ]:
import torch

# Create two sparse tensors
indices1 = torch.tensor([[0, 1], [2, 0]])  # Indices for nonzero values
values1 = torch.tensor([3, 4], dtype=torch.float32)
size1 = (3, 3)

indices2 = torch.tensor([[1, 2], [0, 1]])
values2 = torch.tensor([5, 6], dtype=torch.float32)
size2 = (3, 3)

sparse1 = torch.sparse_coo_tensor(indices1.t(), values1, size1)
sparse2 = torch.sparse_coo_tensor(indices2.t(), values2, size2)

# Concatenating along dim=0
sparse_cat = torch.cat([sparse1, sparse2], dim=0)
print(sparse_cat)


In [ ]:
import torch

# Generate two random 3x4 tensors with binary values (0 or 1)
tensor1 = torch.randint(0, 2, (3, 4), dtype=torch.bool)
tensor2 = torch.randint(0, 2, (3, 4), dtype=torch.bool)

# Perform logical AND operation
result = torch.logical_and(tensor1, tensor2)

print("Tensor 1:")
print(tensor1)

print("\nTensor 2:")
print(tensor2)

print("\nLogical AND Result:")
print(result)


In [ ]:
import torch

# Sparse tensor 1 (3x3)
indices1 = torch.tensor([[0, 1], [2, 0]])  # Positions of 1s
size1 = (3, 3)

# Sparse tensor 2 (3x3)
indices2 = torch.tensor([[1, 2], [0, 1]])
size2 = (3, 3)

# Concatenating along dim=0 (rows) by shifting indices
offset = size1[0]  # Shift rows for second tensor
indices2_shifted = torch.stack([indices2[0] + offset, indices2[1]])

# Combine indices
indices_cat = torch.cat([indices1, indices2_shifted], dim=1)
size_cat = (size1[0] + size2[0], size1[1])  # New size

# Create final sparse tensor (values are all 1s)
sparse_cat = torch.sparse_coo_tensor(indices_cat, torch.ones(indices_cat.shape[1]), size_cat)

print(sparse_cat)


In [ ]:
import torch

# Example data
list_mask_cur = [10, 20, 30, 40, 50]
t_mask_cur = torch.tensor([True, False, True, False, True])

# Filtering values where t_mask_cur is True
filtered_list = [val for val, mask in zip(list_mask_cur, t_mask_cur.tolist()) if mask]

print(filtered_list)  # Output: [10, 30, 50]


In [ ]:
import torch

# Example input tensor (values must be non-negative integers)
x = torch.tensor([0, 1, 1, 2, 2, 2, 3, 3, 3, 3])

# Compute bin counts
counts = torch.bincount(x)

print(counts)


In [ ]:
import torch

# Create a random 2x2x4 tensor with 0s and 1s
tensor = torch.randint(0, 2, (2, 2, 4))

# Find nonzero indices
nonzero_indices = torch.nonzero(tensor)
mask = nonzero_indices[:, 1] == 0 

print("Tensor:\n", tensor)
print("\nNonzero indices:\n", nonzero_indices)
print(mask)

In [ ]:
nonzero_indices[~mask]

In [ ]:
1+torch.zeros(2)

In [ ]:
import torch

t_z = torch.rand(5, 2, 3)  # Example 3D tensor
t_lst_pick0 = torch.tensor([True, False, True, False, True])  # Boolean mask

t_pool0 = t_z[t_lst_pick0, 0, :]
t_pool0[t_pool0 > 0] = 1

print(torch.equal(t_z[t_lst_pick0, 0, :], t_pool0))  # False → `t_z` remains unchanged


In [ ]:
t_z[t_lst_pick0, 0, :]

In [ ]:
def f1(y=3):

    def f2(y):
        y += 3

    f2(y)    
    return y 


In [ ]:
ss = {'1':1,'2':2}

In [ ]:
sum(ss.values())

In [ ]:
aa = [1,2]

In [ ]:
aa.index()

In [ ]:
def first_occurrence_indices(strings):

    index_map = {}
    cur = 0
    for string in strings:
        if string not in index_map:
            index_map[string] = cur
            cur = cur+1
    res = dict(index_map)
    return [res[key] for key in strings]

# Example Usage
strings = ["2", "2", "3", "12","2"]
first_occurrence_indices(strings)



In [ ]:
aa = [1,2]
aa.extend([2])

In [ ]:
import torch

# Example tensors
X = torch.tensor([True, False, True])  # Shape (10,)
Y = torch.tensor([True, 
                  False, False, False, False, False, False, True, True])  # Shape (20,)

# Get indices of True values in Y
true_indices = torch.nonzero(Y, as_tuple=True)[0]

# Modify Y: Set the i-th True value to False if X[i] is False
Y[true_indices] = X

print(Y)


In [ ]:
import torch

# Example tensors
tensor_1 = torch.tensor([[1, 0, 1], [0, 1, 1]])  # Shape (2, 3)
tensor_2 = torch.tensor([[1, 1, 0, 1], [0, 1, 1, 0]])  # Shape (2, 4)

# Expand dimensions for broadcasting
tensor_1_exp = tensor_1.unsqueeze(2)  # Shape: (2, 3, 1)
tensor_2_exp = tensor_2.unsqueeze(1)  # Shape: (2, 1, 4)

# Compute Z[i, j, k] = 1 iff tensor_1[i, j] == 1 and tensor_2[i, k] == 1
Z = (tensor_1_exp & tensor_2_exp).int()  # Shape: (2, 3, 4)

# Print result
print(Z)


In [ ]:
tensor_1

In [ ]:
tensor_2

In [ ]:
import torch

# Create example tensor (shape N=2, M=3, 5)
t_scr_tmp = torch.ones(2, 3, 5)
tm_clb = t_scr_tmp[:,:,0]>=1  # Example mask (shape N=2)

# One-line modification
t_scr_tmp[tm_clb, :, [0, 1]] = 0  # or t_scr_tmp[tm_clb, :, 0:2] = 0

print(t_scr_tmp)

In [ ]:
import torch

# Create a random tensor of shape (N=2, M=3, 5)
Z = torch.randint(0, 2, size=(2, 3, 5)).float()
print("Original tensor:")
print(Z)

# Find indices where Z[i,j,0] >= 7
mask = Z[:, :, 0] >= 1
print("\nMask (where Z[i,j,0] >= 7):")
print(mask)

# Set Z[i,j,4] to 1 where mask is True
Z[:,:,4][mask] = 0

print("\nModified tensor:")
print(Z)


In [ ]:
values = torch.tensor([10, 20, 30, 40], dtype=torch.float32)
indices = torch.tensor([0, 1, 0, 1], dtype=torch.int64)  # assign values to bin 0 or 1

result = torch.zeros(2)
result.scatter_add_(0, indices, values)
# result = [10+30, 20+40] = [40, 60]


In [ ]:
index.shape

In [ ]:
import os
import shutil
from pathlib import Path
import stat

# Set the path to the folder containing subfolders
base_dir = Path("data")

# Loop through all subdirectories
for subfolder in base_dir.iterdir():
    if subfolder.is_dir():
        zip_path = base_dir / f"{subfolder.name}.zip"
        
        # Create zip archive
        shutil.make_archive(str(zip_path.with_suffix('')), 'zip', root_dir=subfolder)
        
        # Remove the original folder after zipping
        shutil.rmtree(subfolder)

        # Make the .zip file read-only
        os.chmod(zip_path, stat.S_IREAD | stat.S_IRGRP | stat.S_IROTH)



In [ ]:
import os
import shutil
from pathlib import Path
import stat

# Define paths
unzipped_dir = Path("Unzipped")
zipped_dir = Path("Zipped")

# Create destination if it doesn't exist
zipped_dir.mkdir(parents=True, exist_ok=True)

# Loop through all subfolders in UnzippedData
for subfolder in unzipped_dir.iterdir():
    if subfolder.is_dir():
        zip_filename = zipped_dir / f"{subfolder.name}.zip"
        
        # Create zip archive in ZippedData
        shutil.make_archive(str(zip_filename.with_suffix('')), 'zip', root_dir=subfolder)

        # Make zip file read-only
        os.chmod(zip_filename, stat.S_IREAD | stat.S_IRGRP | stat.S_IROTH)

        # Remove original folder
        shutil.rmtree(subfolder)

        print(f"Zipped and removed: {subfolder.name}")


In [ ]:
import torch 

def get_batch_end_indices(tc_scr, max_tokens):
    

    return end_indices


def get_batch_ranges_from_ends(end_indices):
    # Prepend 0 as the start of the first batch
    start_indices = torch.cat([torch.tensor([0], device=end_indices.device), end_indices[:-1]])
    return list(zip(start_indices.tolist(), end_indices.tolist()))

tc_scr = torch.tensor([100, 200, 300, 150, 250, 500, 100])
max_tokens = 1000

cumsum = tc_scr.cumsum(0)
total_tokens = cumsum[-1].item()

# Define thresholds: 1000, 2000, ..., up to total_tokens
thresholds = torch.arange(max_tokens, total_tokens + max_tokens, max_tokens, device=tc_scr.device)

# searchsorted gives first index where cumsum >= threshold
end_indices = torch.searchsorted(cumsum, thresholds, right=True)
start_indices = torch.cat([torch.tensor([0], device=end_indices.device), end_indices[:-1]])
ranges = list(zip(start_indices.tolist(), end_indices.tolist()))

for s, e in ranges:
    print(f"Batch: start={s}, end={e}, sum={tc_scr[s:e].sum().item()}")



In [ ]:
thresholds

In [ ]:
Z = torch.tensor([5, 3, 7], dtype=torch.long)
torch.floor(torch.rand_like(Z, dtype=torch.float) * Z).to(torch.int32) + 1

In [ ]:
import torch
Z = torch.tensor([5, 3, 7], dtype=torch.long)

In [ ]:
import torch

# Example input
t_org = torch.tensor([1, 2, 3, 4, 5, 6])      # 1D tensor
t_bsz = torch.tensor([2, 3, 1])           # Block t_bsz: s₁, s₂, s₃
t_rpt = torch.tensor([1, 3, 2])         # Repeat counts: a₁, a₂, a₃

# Compute start indices of each block
t_bgn = torch.cumsum(torch.cat([torch.tensor([0]), t_bsz[:-1]]), dim=0)

# Create an index tensor for each element's original position
# e.g., block 0 repeated 1 time, block 1 repeated 3 times, block 2 repeated 2 times
t_blk = torch.repeat_interleave(t_bgn, t_rpt)
# tensor([0, 2, 2, 2, 5, 5])
t_bls = torch.repeat_interleave(t_bsz, t_rpt)
## tensor([2, 3, 3, 3, 1, 1])

## identify each block using its first index
t_blk = t_blk.repeat_interleave(t_bls) 
## b0,b0,b1,b1,b1,b1,b1,b1,b1,b1,b1,b2,b2
## tensor([0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 5, 5])

## shift starting value 
## tensor([ 0,  0,  2,  2,  2,  5,  5,  5,  8,  8,  8, 11, 12])
tmp2 = torch.cumsum(torch.cat([torch.tensor([0]), t_bls[:-1]]), dim=0).repeat_interleave(t_bls)
total = t_blk.shape[0]
positions = torch.arange(total) - tmp2
indices = positions+t_blk
res = t_org[indices]

In [ ]:
torch.cumsum(torch.cat([torch.tensor([0]), t_bls[:-1]]), dim=0)
# \texttt{cumsum(0,t\_bls[:-1])}

In [ ]:
indices

In [ ]:
res

In [ ]:
import torch

# Example input
t_org = torch.tensor([1, 2, 3, 4, 5, 6])      # 1D tensor
t_bsz = torch.tensor([2, 3, 1])           # Block t_bsz: s₁, s₂, s₃
t_rpt = torch.tensor([1, 3, 2])         # Repeat counts: a₁, a₂, a₃

# Compute start t_idx of each block
t_bgn = torch.repeat_interleave(torch.cumsum(torch.cat([torch.tensor([0]), t_bsz[:-1]]), dim=0), t_rpt)

# Create an index tensor for each element's original position
# e.g., block 0 repeated 1 time, block 1 repeated 3 times, block 2 repeated 2 times
# t_blk = torch.repeat_interleave(t_bgn, t_rpt)
# tensor([0, 2, 2, 2, 5, 5])
t_bls = torch.repeat_interleave(t_bsz, t_rpt)
## tensor([2, 3, 3, 3, 1, 1])

## identify each block using its first index
t_blk = torch.repeat_interleave(t_bgn, t_bls) 
## b0,b0,b1,b1,b1,b1,b1,b1,b1,b1,b1,b2,b2
## tensor([0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 5, 5])

## shift starting value 
## tensor([ 0,  0,  2,  2,  2,  5,  5,  5,  8,  8,  8, 11, 12])
t_csm = torch.cumsum(torch.cat([torch.tensor([0]), t_bls[:-1]]), dim=0).repeat_interleave(t_bls)
i_blk = t_blk.shape[0]
t_pos = torch.arange(i_blk) - t_csm
t_idx = t_pos+t_blk
t_rbk = t_org[t_idx]

In [ ]:
torch.arange(total) - positions

In [ ]:
import torch

# Example tensor with consecutive duplicates
x = torch.tensor([1, 1, 2, 2, 2, 3, 1, 1, 4])

# Apply unique_consecutive
unique_vals = torch.unique_consecutive(x, return_inverse=True)

print(unique_vals)


In [ ]:
import inspect

def get_var_name(var):
    frame = inspect.currentframe().f_back
    for name, val in frame.f_locals.items():
        if val is var:
            return name
    return None


In [ ]:
x = 42
y = x
print(get_var_name(x))  # Output: 'x'

t_sid = [1, 2, 3]
print(get_var_name(t_sid))  # Output: 't_sid'


In [ ]:
import torch 
weights = torch.tensor([[0, .10, .3, .0100],[1000, 10, .3, .0100]], dtype=torch.float) # create a tensor of weights
torch.multinomial(weights, 1)

In [ ]:
def extsampling(t_edg, c_edg, t_sgm):

    res             = torch.zeros_like(t_sgm, dtype=torch.bool)
    t_idx           = torch.argsort(t_edg)
    t_inv           = torch.empty_like(t_idx)
    t_inv[t_idx]    = torch.arange(len(t_idx))

    st_sgm          = t_sgm[t_idx]
    i_max           = c_edg.max()
    i_num           = c_edg.shape[0]
    t_msk = torch.arange(i_max).unsqueeze(0) < c_edg.unsqueeze(1)
    
    t_mtx           = torch.zeros_like(t_msk, dtype=t_sgm.dtype)
    t_mtx[t_msk]    = t_sgm

    t_smp = torch.multinomial(t_mtx, num_samples=1).squeeze(1) 
    t_gps = torch.cat([torch.tensor([0]), c_edg.cumsum(0)[:-1]]) # group starts 
    res[t_gps + t_smp] = True 
    return res[t_inv]



In [ ]:
import torch

# Original tensor
x = torch.tensor([[3, 100],
                  [1, 200],
                  [2, 300]])

# Sort by column 0
sort_idx          = torch.argsort(x[:, 0])
inv_idx           = torch.empty_like(sort_idx)
inv_idx[sort_idx] = torch.arange(len(sort_idx))

sorted_x    = x[sort_idx]
recovered_x = sorted_x[inv_idx]

print("Sorted x:\n", sorted_x)
print("Recovered x:\n", recovered_x)




In [ ]:
import torch

probs = torch.tensor([0.1, 0.9, 0.3, 0.7, 0.2, 0.2, 0.6, 1.0, 0.5, 0.5])
c_edg = torch.tensor([2, 2, 3, 1, 2])

i_max = c_edg.max()
i_num = len(c_edg)

t_msk = torch.zeros((i_num, i_max), dtype=torch.bool)
idx = torch.arange(i_max)
t_msk = idx.unsqueeze(0) < c_edg.unsqueeze(1)

t_mtx = torch.zeros_like(t_msk, dtype=probs.dtype)
t_mtx[t_msk] = probs

# Step 2: Sample one index per group from padded probs
sampled_local = torch.multinomial(t_mtx, num_samples=1).squeeze(1)  # [i_num]

# Step 3: Convert to global indices
group_start = torch.cat([torch.tensor([0]), c_edg.cumsum(0)[:-1]])
global_indices = group_start + sampled_local

print(global_indices)  # shape: [i_num], each index from global `probs`


In [ ]:
torch.multinomial(padded_probs, num_samples=1)

In [ ]:
import torch

x = torch.tensor([0,0, 2, 2, 3, 7])

# Find where values change
is_new = torch.ones_like(x, dtype=torch.bool)
is_new[1:] = x[1:] != x[:-1]

# Assign group ids
group_ids = torch.cumsum(is_new, dim=0) - 1


In [ ]:
group_ids

In [ ]:
import xgboost as xgb
import numpy as np

# Dummy data
X = np.random.rand(10, 5).astype(np.float32)
dtest = xgb.DMatrix(X)
params = {
    "objective": "reg:squarederror",
    "base_score": 0.0,
    "tree_method": "hist"
}

model = xgb.train(params, dtrain=dtest, num_boost_round=0)

y_pred = model.predict(dtest)

print("Predictions:", y_pred)



Predictions: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [18]:
dtest

In [8]:
import torch

t1 = torch.tensor([1, 0, 1, 0], dtype=torch.bool)
t2 = torch.randint(0, 2, (4, 4), dtype=torch.bool)

result = torch.logical_and(t1, t2)
print(result.shape)  # torch.Size([4, 12])


torch.Size([4, 4])


In [9]:
result

tensor([[ True, False,  True, False],
        [False, False,  True, False],
        [False, False,  True, False],
        [ True, False, False, False]])

In [10]:
t1

tensor([ True, False,  True, False])

In [11]:
t2

tensor([[ True, False,  True,  True],
        [False, False,  True,  True],
        [False, False,  True, False],
        [ True, False, False, False]])

In [19]:
import xgboost as xgb
import numpy as np

# Dummy features
X = np.random.rand(100, 10).astype(np.float32)
y = np.zeros(100, dtype=np.float32)  # all targets are 0

dtrain = xgb.DMatrix(X, label=y)

params = {
    "objective": "reg:squarederror",
    "tree_method": "hist",
    "max_depth": 1,
    "learning_rate": 1.0,
    "nthread": 1
}

# One boosting round is enough to learn constant output
model = xgb.train(params, dtrain, num_boost_round=1)


In [20]:
model